[tool.poetry]
name = "seppl"
version = "0.1.0"
description = "AI-Powered E-Learning App for Argument Analysis"
authors = ["Gregor Betz <gregor.betz@kit.edu>"]
license = "APACHE 2.0"

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.7.0"
google-cloud-firestore = "^2.3.4"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.931"
pylint = "^2.12.2"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
